### ISSUE TITLE
Creating of a pool hangs when used with Puma

### ISSUE THREAD

**Issue by tikh** [celluloid/celluloid-pool#15]
We "lazily" create a pool in an action and save a it for any further actions. But after updating to the latest celluloid gem it started hanging just on invoking `pool` method:
```
@pool ||= MyOperation.pool(size: 4)
```
It used to work well with 0.16 version of celluloid.

**Comment by digitalextremist** [comment]
Please provide reproduction, or sample of code?

**Comment by digitalextremist** [comment]
i.e. your actual actors.

**Comment by tarcieri** [comment]
Note this pattern isn't thread safe. Do you have more than one thread
pushing work into the pool?

>

-- 
Tony Arcieri

**Comment by tikh** [comment]
Just created a small app that reproduces the issue: https://github.com/tikh/celluloid_reproduce_bug

**Comment by tikh** [comment]
In our setup we have several Puma processes but each process has one thread for processing requests. 
Here is an action and simplest "actor" possible:
https://github.com/tikh/celluloid_reproduce_bug/blob/master/app/controllers/welcome_controller.rb

**Comment by digitalextremist** [comment]
Thanks @tikh ... If anyone who frequently/ever uses `Rails` sees this, please jump on in while I try to come back to this sooner than later.

**Comment by digitalextremist** [comment]
Just coming back to say, @tikh -- your level of reproduction code is unlike what most people ever get [when they ask](https://github.com/celluloid/celluloid-pool/issues/15#issuecomment-224393632) and I just want to commend/thank you in the interim.

**Comment by tikh** [comment]
Looks like when Celluloid is being required by `Bundler.require` at the application start up, it also creates some 4 threads that are needed for the further work. But the real process that handles web requests is a fork of the initial one, and with these threads of course. 

It's easy to disable "requiring" of celluloid gem and do it after fork. This will even work in my sample Rails project. But in real project I still need Celluloid modules loaded before fork. 

So the question is if there a way to require Celluloid modules at start up and do creation of autostart threads after the fork?

**Comment by digitalextremist** [comment]
Ah, great factoid to include. Very common `Rails` issue. Someone with `Rails` will hopefully chime in shortly with the answer to this, otherwise definitely search the issues in `Celluloid` itself keying in on `fork` and `rails`

**Comment by helper2424** [comment]
Yep, problem in fork. So I fix It:
1) Change your Gemfile:
`gem 'celluloid', require: ['celluloid/current']` -> `gem 'celluloid', require: ['celluloid']`
2) In config/puma.rb
```
on_worker_boot do
  ActiveRecord::Base.establish_connection
end
```
->
```
on_worker_boot do
  ActiveRecord::Base.establish_connection

  $CELLULOID_BACKPORTED = false
  Celluloid.start
end
```
Last changes start celluloid inside forked puma process

**Comment by tikh** [comment]
Thank you, @helper2424. That works!

**Comment by helper2424** [comment]
Nice to help you.
