### ISSUE TITLE
Failure/Error: expect(Celluloid::Actor[:example_pool].size).to be size

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid-pool#3]
@e2 is saying the issue is that `:size` is not coming into the initializer, but I'm catching the `4` value actually *was* given to `initialize` somewhere.

Strangely, it's getting there magically though. This is sent onward by `prepare_options`:

```{:args=>"foo", :size=>3, :as=>:example_pool, :block=>nil}```

This is what `PoolManager.initialize` gets: `[4, ["foo"], {:args=>["foo"]}]`

That `4` was the value of @size, and that hash was all of `options` displayed.

Uh.

**Comment by digitalextremist** [comment]
Magically disappeared after @e2 posted changes to `celluloid/0.17.0-prerelease`

**Comment by e2** [comment]
@digitalextremist - the instance vars were set on the supervisor, and not on the Member (the binding was wrong) - and so the PoolManager defaulted the size to the number of cores. 

Which is how we now also know Travis has 32 cores... ;)

**Comment by digitalextremist** [comment]
That `32` is good to know, but where was the `4` coming from?

**Comment by e2** [comment]
Number of cores on your computer?
