### ISSUE TITLE
Support a pool size of 1

### ISSUE THREAD

**Issue by nickelser** [celluloid/celluloid-pool#7]
For explicitly non-threadsafe actors, would be nice to support a pool size of 1. (especially in the case of a user-configurable pool size).

Seems to be hardcoded to at least 2 here: https://github.com/celluloid/celluloid-pool/blob/master/lib/celluloid/supervision/container/pool.rb#L22

**Comment by digitalextremist** [comment]
The default is hard-coded to `2`, but you can specify `1`.

**Comment by nickelser** [comment]
You are totally correct, sorry for the spurious issue :+1:

**Comment by digitalextremist** [comment]
No problem. Feel free to report anything you need to.
